repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
      - id: mixed-line-ending
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-yaml
        exclude: "not_rendered.yml|invalid-config.yaml"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff
        types_or: [ python, pyi ]
        args: [ --fix ]
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: local
    hooks:
      - id: pytest
        name: Run pytest
        entry: poetry run pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
        stages: [push]