---

volumes:
  postgres_data_local: {}

version: "3.7"
services:
  db:
    image: postgres:12.3-alpine
    volumes:
      - postgres_data_local:/var/lib/postgresql/data
      - ./tests/integration/db_dump:/dumps
    environment:
      POSTGRES_PASSWORD: ecosystem
      POSTGRES_DB: public
    ports:
      - "5432:5432"
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120

  db-setup:
    depends_on:
      - dockerlocalhost
    build:
      context: ./data-load
      dockerfile: ../Dockerfile.flyway
    command: ./gradlew flywayMigrate
    volumes:
      - ./data-load/schema/:/schema
    environment:
      PG_HOST: dockerlocalhost
      PG_PORT: 5432
      DATABASE_NAME: public
      DATABASE_USER: postgres
      DATABASE_PASSWORD: ecosystem
      DATABASE_ROLES: admin,api,pipeline,readonly
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: ecosystem
ı