name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies using Poetry
        run: poetry install --no-interaction --no-root --without notebook,profiling

      - name: Run unit tests
        run: poetry run pytest -m "not nondeterministic"

  flaky-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - run: pip install poetry
      - run: poetry install --no-interaction --no-root --without notebook,profiling

      - name: Run non-deterministic (flaky) tests
        run: poetry run pytest -m "nondeterministic"
        continue-on-error: true
